@startuml
autonumber "<b>(#)"

participant App #white
participant Main.update as MU #white
participant Child.update as CU #white
participant GrandChild.update as GC #white

App -> MU: update
MU -> CU: update
CU -> GC: update
GC --> CU: (model, command)
CU --> MU: (model, command)
MU -> App : (model, command)

@enduml
