@startuml
autonumber
participant program #white
participant update #white
participant view #white

program -> view : Affiche la vue
|||
view -> program : Déclenche un message, i.e. Expand
program -> update : Envoie le message avec l'état courant
update --> program : Renvoie l'état mis à jour + des commandes
program -> view : Affiche la vue
@enduml
