@startuml

autonumber "<b>(#)"

participant Browser #white
participant Navigation #white
participant init #white
participant parse #white
participant urlUpdate #white
participant View #white

Navigation -> parse : Current location
parse --> Navigation : Matched Route
Navigation -> init : Matched Route
init --> Navigation : Initial model
Navigation -> View : Model
View --> Navigation : Rendered view

newpage

autonumber 1 "<b>(#)"
Browser -> Navigation : Location change event
Navigation -> parse : New location
parse --> Navigation : Matched Route
Navigation -> urlUpdate : Matched Route
urlUpdate --> Navigation : Updated model
Navigation -> View : Model
View --> Navigation : Rendered view

@enduml

